version: 0.2
# Based on the Docker documentation, must include the DOCKER_CLI_EXPERIMENTAL environment variable
# https://docs.docker.com/engine/reference/commandline/manifest/    

phases:
    pre_build:
        commands:
            - echo Logging in to Amazon ECR...
            - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    build:
        commands:
            - echo Build started on `date`
            - echo Building the Docker manifest...   
            - export DOCKER_CLI_EXPERIMENTAL=enabled
            - VARIANT_TAGS=${TOMCAT_VARIANT_TAGS:-8.5-jdk8-corretto 8.5-jdk8-corretto-al2 8.5-jdk11-corretto 8.5-jdk11-corretto-al2 9-jdk11-corretto 9-jdk11-corretto-al2 9-jdk17-corretto 9-jdk17-corretto-al2 10-jdk11-corretto 10-jdk11-corretto-al2}
            - for v in $VARIANT_TAGS; do docker manifest create public.ecr.aws/$IMAGE_REPO_NAME/tomcat-xslt:${v} public.ecr.aws/$IMAGE_REPO_NAME/tomcat-xslt:${v}arm64v8 public.ecr.aws/$IMAGE_REPO_NAME/tomcat-xslt:${v}amd64 ; done
            - for v in $VARIANT_TAGS; do docker manifest annotate --arch arm64 public.ecr.aws/$IMAGE_REPO_NAME/tomcat-xslt:${v} public.ecr.aws/$IMAGE_REPO_NAME/tomcat-xslt:${v}arm64v8 ; done
            - for v in $VARIANT_TAGS; do docker manifest annotate --arch amd64 public.ecr.aws/$IMAGE_REPO_NAME/tomcat-xslt:${v} public.ecr.aws/$IMAGE_REPO_NAME/tomcat-xslt:${v}amd64 ; done
            - echo Build CDI started on `date`
            - echo Building CDI the Docker manifest...   
            - export DOCKER_CLI_EXPERIMENTAL=enabled
            - CDI_VARIANT_TAGS=${TOMCAT_CDI_VARIANT_TAGS:-9-jdk11-corretto 9-jdk11-corretto-al2 9-jdk17-corretto 9-jdk17-corretto-al2 10-jdk11-corretto 10-jdk11-corretto-al2}
            - for v in $VARIANT_TAGS; do docker manifest create public.ecr.aws/$IMAGE_REPO_NAME/tomcat-xslt-cdi:${v} public.ecr.aws/$IMAGE_REPO_NAME/tomcat-xslt-cdi:${v}arm64v8 public.ecr.aws/$IMAGE_REPO_NAME/tomcat-xslt-cdi:${v}amd64 ; done
            - for v in $VARIANT_TAGS; do docker manifest annotate --arch arm64 public.ecr.aws/$IMAGE_REPO_NAME/tomcat-xslt-cdi:${v} public.ecr.aws/$IMAGE_REPO_NAME/tomcat-xslt-cdi:${v}arm64v8 ; done
            - for v in $VARIANT_TAGS; do docker manifest annotate --arch amd64 public.ecr.aws/$IMAGE_REPO_NAME/tomcat-xslt-cdi:${v} public.ecr.aws/$IMAGE_REPO_NAME/tomcat-xslt-cdi:${v}amd64 ; done
            
    post_build:
        commands:
            - echo Build completed on `date`
            - echo Pushing the Docker image...
            - VARIANT_TAGS=${TOMCAT_VARIANT_TAGS:-8.5-jdk8-corretto 8.5-jdk8-corretto-al2 8.5-jdk11-corretto 8.5-jdk11-corretto-al2 9-jdk11-corretto 9-jdk11-corretto-al2 9-jdk17-corretto 9-jdk17-corretto-al2 10-jdk11-corretto 10-jdk11-corretto-al2}
            - CDI_VARIANT_TAGS=${TOMCAT_CDI_VARIANT_TAGS:-9-jdk11-corretto 9-jdk11-corretto-al2 9-jdk17-corretto 9-jdk17-corretto-al2 10-jdk11-corretto 10-jdk11-corretto-al2}
            - for v in $VARIANT_TAGS; do docker manifest push public.ecr.aws/$IMAGE_REPO_NAME/tomcat-xslt:${v} ; done
            - for v in $CDI_VARIANT_TAGS; do docker manifest push public.ecr.aws/$IMAGE_REPO_NAME/tomcat-xslt-cdi:${v} ; done
