<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

	<xsl:output method="xml" version="1.0" encoding="UTF-8"
		indent="yes" />

    <xsl:template match="/">
        <xsl:comment>Generated by web-distributable.xsl for <xsl:value-of select="name(child::*[1])" /></xsl:comment>
        <web-app>
            <xsl:copy-of select="child::*[1]/attribute::*" />
            <xsl:copy-of select="child::*[1]/child::*" />

            <xsl:if test="not(child::*[1]/distributable)">
                <distributable />
            </xsl:if>
        </web-app>
    </xsl:template>

</xsl:stylesheet>