name: Docker Hub build images CI

on:
  release:
    types: [published]
  workflow_dispatch:
  
env:
  BUILDER_OPT: "--quiet"
  BUILD_PLATFORM: "linux/amd64,linux/arm64"
  MY_DOCKER_REGISTRY: myquartz/
  USING_BUILDX: "yes"
  PUSH: "yes"
  LATEST_TAG: "11-jdk17"
  TOMCAT_VARIANT_TAGS: "8.5-jdk8 8.5-jdk11 9-jdk11 9-jdk11-temurin 9-jdk11-corretto 9-jdk17 9-jdk17-temurin 9-jdk17-corretto 10-jdk11 10-jdk11-temurin 10-jdk11-corretto 10-jdk17 11-jdk17 11-jdk21"
  TOMCAT_CDI_VARIANT_TAGS: "9-jdk11 9-jdk11-temurin 9-jdk11-corretto 9-jdk17 9-jdk17-temurin 9-jdk17-corretto 10-jdk11 10-jdk11-temurin 10-jdk11-corretto 10-jdk17 11-jdk17 11-jdk21"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "myquartz/tomcat-xslt-builder"
      - name: Build and push Tomcat
        run: bash build-images.sh "$TOMCAT_VARIANT_TAGS" "no" && bash build-images.sh "$TOMCAT_CDI_VARIANT_TAGS" "yes"

