name: Docker Hub build images CI

on:
  push:
    branches:
      - "main"
env:
  #BUILDER_OPT: "--quiet --builder cloud-myquartz-tomcat-xslt-builder"
  BUILDER_OPT: "--quiet"
  BUILD_PLATFORM: "linux/amd64,linux/arm64"
  MY_DOCKER_REGISTRY: myquartz/
  USING_BUILDX: "yes"
  PUSH: "yes"
  TOMCAT_VARIANT_TAGS: "8.5-jdk8 8.5-jdk11"
  TOMCAT_CDI_VARIANT_TAGS: "9-jdk11 9-jdk17"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "myquartz/tomcat-xslt-builder"
      - name: Build and push Tomcat
        run: bash build-images.sh "$TOMCAT_VARIANT_TAGS" "no"
      - name: Build and push Tomcat CDI
        run: bash build-images.sh "$TOMCAT_CDI_VARIANT_TAGS" "yes"
